server:
  port: 8080

spring:
  application:
    name: Euphoria_Ecommerce
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres?currentSchema=euphoria_ecommerce
    username: postgres
    password:
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: ""
    password: ""
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  jwt:
    SECRET_KEY: "7ebe8d71e6ea4ae6192cb0a85e640221058c28adb6b5564b29f7faf8bc61b2f6"